2021-05-20 20:50:15,741          root     INFO: Starting script
2021-05-20 20:50:16,760          root     INFO: Parsing Folha de S.Paulo - Opini√£o - Principal
2021-05-20 20:50:17,547          root     INFO: Parsing Folha de S.Paulo - Poder - Principal
2021-05-20 20:50:22,113          root    ERROR: RSS
Traceback (most recent call last):
  File "/home/runner/work/NYTdiff/NYTdiff/.venv/lib/python3.6/site-packages/feedparser.py", line 398, in __getattr__
    return self.__getitem__(key)
  File "/home/runner/work/NYTdiff/NYTdiff/.venv/lib/python3.6/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nytdiff.py", line 527, in main
    rss.parse_rss()
  File "nytdiff.py", line 491, in parse_rss
    logging.info('Parsing %s', r.feed.title)
  File "/home/runner/work/NYTdiff/NYTdiff/.venv/lib/python3.6/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'title'
2021-05-20 20:50:22,114          root     INFO: Finished script
